@{
    ExcludeRules=@(
        'PSAvoidUsingConvertToSecureStringWithPlainText',
        'PSAvoidUsingPlainTextForPassword',
        'PSAvoidUsingUsernameAndPasswordParams',
        'PSAvoidUsingWriteHost',
        'PSPossibleIncorrectComparisonWithNull',
        'PSUseShouldProcessForStateChangingFunctions'
    )
}